title: PCT 2019
author: Alex
email: kincadealex@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  awesome description!

# social links
twitter_username: alexkincade
github_username:  rookkin

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
